// This unit is autogenerated. Do not edit it manually.
// Source: JSON entered in editor
// Date: 4/11/2024 11:04:16 AM

unit Unit4;

interface

uses
  System.Classes, System.JSON.Serializers, System.Generics.Collections, System.JSON.Converters;

type
  TRequiredData = class;

  TJsonListConverterTRequiredData = class(TJsonListConverter<TRequiredData>);

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TRequiredData = class(TPersistent)
  private
    Fid: string;
    FlocId: Integer;
    FlocName: string;
    FvisitDateTime: Double;
    FvisitType: string;
    FvisitString: string;
  public
    property id: string read Fid write Fid;
    property locId: Integer read FlocId write FlocId;
    property locName: string read FlocName write FlocName;
    property visitDateTime: Double read FvisitDateTime write FvisitDateTime;
    property visitType: string read FvisitType write FvisitType;
    property visitString: string read FvisitString write FvisitString;
  end;

  [JsonSerialize(TJsonMemberSerialization.Public)]
  TMyData = class(TPersistent)
  private
    Fid: string;
    FisNational: Boolean;
    FpatientId: Integer;
    Fcolor: string;
    Falign: string;
    FrequiredData: TObjectList<TRequiredData>;
  public
    constructor Create;
    destructor Destroy; override;
    property id: string read Fid write Fid;
    property isNational: Boolean read FisNational write FisNational;
    property patientId: Integer read FpatientId write FpatientId;
    property color: string read Fcolor write Fcolor;
    property align: string read Falign write Falign;
    [JsonConverter(TJsonListConverterTRequiredData)]
    property requiredData: TObjectList<TRequiredData> read FrequiredData;
  end;

implementation

uses
  System.SysUtils;

constructor TMyData.Create;
begin
  inherited Create;
  FrequiredData := TObjectList<TRequiredData>.Create(True);
end;

destructor TMyData.Destroy;
begin
  FreeAndNil(FrequiredData);
  inherited Destroy;
end;

initialization

  RegisterClass(TRequiredData);
  RegisterClass(TMyData);

end.
